add prioritization of green over bronze in get_upw.R and test-get_upw.R
OAmonitor/OAmonitor pull request #17
Opened 2021-04-22 12:01 UTC by bmkramer

in progress - still error in test

2021-04-22 12:14 UTC, bmkramer commented
test-get_upw.R gives error 
-- 1. Error: green is prioritized over bronze (@test-get_upw.R#106)  ---------------
'list' object cannot be coerced to type 'double'

2021-06-04 14:35 UTC, bvreede requested changes
Looks good, just check the export of an — as far as I recall — as yet incomplete function.

2021-06-04 14:35 UTC, bvreede commented on NAMESPACE
> +export(open_df)
Where does this come from? That has nothing to do with this PR?

2021-06-04 14:43 UTC, bvreede approved these changes

2021-06-04 14:46 UTC, merged